language: python
python:
- 3.6.1
branches:
  only:
  - test
  - prod
jobs:
  include:
  - stage: test
    script:
     - python -m doctest -v  unnecessary_math.py
  - stage: prod
    script:
      - python test_um_unittest.py

