language: python
python:
- 3.6.1
branches:
  only:
  - test
  - prod
stages:
- name: test
  if: branch = test
- name: prod
if: branch = prod
jobs:
  include:
  - stage: test
    script:
     - python test_um_unittest.py
  - stage: prod
    script:
     - python -m doctest -v  unnecessary_math.py
notifications: 
email:
  on_failure: change
  on_success: change
